server:
  port: 8072

spring:
  application:
    name: "bank-microservice"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${DB_CONTAINER_NAME}:3306/alinedb"
    initialization-mode: always

app:
  sms:
    enable: false
  email:
    enable: false
  security:
    secret-key: "${SECRET_KEY}"
    jwt:
      secret-key: "${SECRET_KEY}"

